"""empty message

Revision ID: 00a6a8b9d2ab
Revises: 225ad98c223d
Create Date: 2020-04-26 10:16:49.916758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a6a8b9d2ab'
down_revision = '225ad98c223d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('published', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motorcycles', 'published')
    # ### end Alembic commands ###
