"""Added column 'text'

Revision ID: 5218547536e3
Revises: fdcb10195343
Create Date: 2020-04-13 06:48:57.786259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5218547536e3'
down_revision = 'fdcb10195343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motorcycles', 'text')
    # ### end Alembic commands ###
