"""added published to motorcycles

Revision ID: d8be1bba30b1
Revises: 4a15bf1a1a15
Create Date: 2020-04-26 10:42:24.849502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8be1bba30b1'
down_revision = '4a15bf1a1a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('published', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motorcycles', 'published')
    # ### end Alembic commands ###
