"""added published to motorcycles

Revision ID: ecc40abfe181
Revises: d8be1bba30b1
Create Date: 2020-04-26 10:44:56.864104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc40abfe181'
down_revision = 'd8be1bba30b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorcycles', sa.Column('published', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motorcycles', 'published')
    # ### end Alembic commands ###
